

/*Autogenerated file*/

#include "_proto.h"
#include "utLib/inc/_emod.h"

void
test_emod (void)
{

  int err;

  hdr ("Testing of emod module started");

  err = 10;

  retVal = errno2EC (err);
  EXEC_TSTCASE (&tstCase, "Err = 10 in errno2EC", (retVal == -10), retVal,
		"Errno not proper", 0);

  retVal = strcmp (strerror (err), ec2ES (errno2EC (err)));
  EXEC_TSTCASE (&tstCase, "Error msg from strerror and ec2ES compare",
		(!retVal), retVal, strerror (err), 0);

  //;
  EXEC_TSTCASE (&tstCase, "Error msg for 0", (ec2ES (0) == NULL), 0,
		ec2ES (0), 0);

  //;
  EXEC_TSTCASE (&tstCase, "Error msg for 1", (ec2ES (1) == NULL), 0,
		ec2ES (1), 0);

  //;
  EXEC_TSTCASE (&tstCase, "Error msg for ERR_BASE_VALUE",
		(ec2ES (-ERR_BASE_VALUE) == NULL), 0, ec2ES (-ERR_BASE_VALUE),
		0);

  //;
  EXEC_TSTCASE (&tstCase, "Error msg for ERR_BASE_VALUE+MAX_ERR_STRING_SIZE",
		(ec2ES (-ERR_BASE_VALUE - MAX_ERR_STRING_SIZE) == NULL), 0,
		ec2ES (-ERR_BASE_VALUE - MAX_ERR_STRING_SIZE), 0);

#if 0
  retVal =
    strcmp (ec2ES (-ERR_BASE_VALUE - MAX_ERR_STRING_SIZE + 1),
	    "Invalid error code value");
  EXEC_TSTCASE (&tstCase,
		"Error msg for ERR_BASE_VALUE+MAX_ERR_STRING_SIZE-1",
		(!retVal), retVal,
		ec2ES (-ERR_BASE_VALUE - MAX_ERR_STRING_SIZE + 1), 0);
#endif

  //;
  EXEC_TSTCASE (&tstCase, "Error msg for SUCCESS", (ec2ES (SUCCESS) == NULL),
		0, ec2ES (SUCCESS), 0);

  retVal = strcmp (ec2ES (FAILURE), "Failed");
  EXEC_TSTCASE (&tstCase, "Error msg for FAILURE", (!retVal), retVal,
		ec2ES (FAILURE), 0);

  hdr ("Testing of emod module compleated");
}
