
/*Autogenerated file*/

#include "_proto.h"
#include "../../../../src/utLib/inc/_lmod.h"
#define TEST_FILE "/tmp/testlmod"

void
test_lmod (void)
{

  bs_lmodCls lobj = NULL;
  bs_fmodCls rdwrF = NULL;

  hdr ("Testing of lmod module started");

  retVal = bs_lmodInit (&lobj, false, false, false, NULL, iMObj);
  EXEC_TSTCASE (&tstCase, " Initialize the lmod object. ", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = bs_lmodFin (&lobj, iMObj);
  EXEC_TSTCASE (&tstCase, " Finalise the lmod object. ", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = bs_lmodInit (&lobj, true, false, false, NULL, iMObj);
  EXEC_TSTCASE (&tstCase, " Initialize the lmod object with syslog. ", retVal,
		retVal, ec2ES (retVal), 0);

  retVal = bs_lmodFin (&lobj, iMObj);
  EXEC_TSTCASE (&tstCase, " Finalise the lmod object with syslog. ", retVal,
		retVal, ec2ES (retVal), 0);

  retVal = bs_lmodInit (&lobj, false, true, true, NULL, iMObj);
  EXEC_TSTCASE (&tstCase,
		" Initialize the lmod object with quite and verbose flag. ",
		retVal, retVal, ec2ES (retVal), 0);

  retVal = bs_lmodFin (&lobj, iMObj);
  EXEC_TSTCASE (&tstCase,
		" Finalise the lmod object with quite and verbose flag set. ",
		retVal, retVal, ec2ES (retVal), 0);

  retVal = bs_lmodInit (&lobj, true, true, true, NULL, iMObj);
  EXEC_TSTCASE (&tstCase,
		" Initialize the lmod object with quite, verbose and syslog flag set. ",
		retVal, retVal, ec2ES (retVal), 0);

  retVal = bs_lmodFin (&lobj, iMObj);
  EXEC_TSTCASE (&tstCase, " Finalise the lmod object with all flags set. ",
		retVal, retVal, ec2ES (retVal), 0);

  retVal = bs_fmodInit (&rdwrF, iMObj);
  EXEC_TSTCASE (&tstCase, " Initialize a file object. ", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = bs_fCreate (rdwrF, TEST_FILE, 0755);
  EXEC_TSTCASE (&tstCase, " Finalise the fmod object. ", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = bs_lmodInit (&lobj, true, true, true, rdwrF, iMObj);
  EXEC_TSTCASE (&tstCase,
		" Initialize the lmod object with all flags and a file object. ",
		retVal, retVal, ec2ES (retVal), 0);

  bs_log (lobj, LVL_INFO, PO_LOG, "%s", "\nTest info message VQ");

  bs_log (lobj, LVL_DEBUG, PO_LOG, "%s", "\nTest debug message VQ");

  bs_log (lobj, LVL_ERROR, PO_LOG, "%s", "\nTest err message VQ");

  bs_unsetVerbose (lobj);

  bs_log (lobj, LVL_INFO, PO_LOG, "%s", "\nTest info message NVQ");

  bs_log (lobj, LVL_DEBUG, PO_LOG, "%s", "\nTest debug message NVQ");

  bs_log (lobj, LVL_ERROR, PO_LOG, "%s", "\nTest err message NVQ");

  bs_setVerbose (lobj);

  bs_unsetQuite (lobj);

  bs_log (lobj, LVL_INFO, PO_LOG, "%s", "\nTest info message VNQ");

  bs_log (lobj, LVL_DEBUG, PO_LOG, "%s", "\nTest debug message VNQ");

  bs_log (lobj, LVL_ERROR, PO_LOG, "%s", "\nTest err message VNQ");

  bs_setQuite (lobj);

  bs_unsetVerbose (lobj);

  bs_unsetQuite (lobj);

  bs_log (lobj, LVL_INFO, PO_LOG, "%s", "\nTest info message NVNQ");

  bs_log (lobj, LVL_DEBUG, PO_LOG, "%s", "\nTest debug message NVNQ");

  bs_log (lobj, LVL_ERROR, PO_LOG, "%s", "\nTest err message NVNQ");

  bs_setVerbose (lobj);

  bs_setQuite (lobj);

  bs_log (lobj, LVL_INFO, PF_LOG, "%s", "\nTest info message VQ");

  bs_log (lobj, LVL_DEBUG, PF_LOG, "%s", "\nTest debug message VQ");

  bs_log (lobj, LVL_ERROR, PF_LOG, "%s", "\nTest err message VQ");

  bs_unsetVerbose (lobj);

  bs_log (lobj, LVL_INFO, PF_LOG, "%s", "\nTest info message NVQ");

  bs_log (lobj, LVL_DEBUG, PF_LOG, "%s", "\nTest debug message NVQ");

  bs_log (lobj, LVL_ERROR, PF_LOG, "%s", "\nTest err message NVQ");

  bs_setVerbose (lobj);

  bs_unsetQuite (lobj);

  bs_log (lobj, LVL_INFO, PF_LOG, "%s", "\nTest info message VNQ");

  bs_log (lobj, LVL_DEBUG, PF_LOG, "%s", "\nTest debug message VNQ");

  bs_log (lobj, LVL_ERROR, PF_LOG, "%s", "\nTest err message VNQ");

  bs_setQuite (lobj);

  bs_unsetVerbose (lobj);

  bs_unsetQuite (lobj);

  bs_log (lobj, LVL_INFO, PF_LOG, "%s", "\nTest info message NVNQ");

  bs_log (lobj, LVL_DEBUG, PF_LOG, "%s", "\nTest debug message NVNQ");

  bs_log (lobj, LVL_ERROR, PF_LOG, "%s", "\nTest err message NVNQ");

  retVal = bs_lmodFin (&lobj, iMObj);
  EXEC_TSTCASE (&tstCase,
		" Finalise the lmod object with all flags and the file object. ",
		retVal, retVal, ec2ES (retVal), 0);

  retVal = bs_fmodFin (&rdwrF, iMObj);
  EXEC_TSTCASE (&tstCase,
                " Finalise the fmod object",
		retVal, retVal, ec2ES (retVal), 0);

  hdr ("Testing of lmod module compleated");
}
