
/*Autogenerated file*/

#include "_proto.h"
#include "../../../../src/utLib/inc/_mmod.h"

void
test_mmod (void)
{

  char *testBuffer = NULL;
  bs_mmodCls validMemLoc = NULL;

  hdr ("Testing of mmod module started");

  retVal = bs_mmodInit (&validMemLoc);
  EXEC_TSTCASE (&tstCase, "Check for initization of a memory object.", retVal,
		retVal, ec2ES (retVal), 0);

  retVal = bs_allocMem (validMemLoc, 10, (void *) &testBuffer);
  EXEC_TSTCASE (&tstCase, "Check for Memory allocations.", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = bs_freeMem (validMemLoc, (void *) &testBuffer);
  EXEC_TSTCASE (&tstCase, "Check for Memory Freeing.", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = bs_mmodFin (&validMemLoc);
  EXEC_TSTCASE (&tstCase, "Check for finalization of a memory object.",
		retVal, retVal, ec2ES (retVal), 0);

  hdr ("Testing of mmod module compleated");
}
