
/*Autogenerated file*/

#include "_proto.h"
#include "../../../../src/utLib/inc/_tmod.h"

void tstTmrHndlr (int signum);
genErr_t testTimer (void);

int state = 0;
void
tstTmrHndlr (int signum)
{
  (void)signum;
  state = 1;
}

genErr_t
testTimer (void)
{
  sleep (1);
  if (state)
    return SUCCESS;
  return FAILURE;
}

void
test_tmod (void)
{

  bs_tmodCls tObj = NULL;

  hdr ("Testing of tmod module started");

  retVal = bs_tmodInit (&tObj, iMObj);
  EXEC_TSTCASE (&tstCase, " Initialize the timer module ", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = bs_registerTimerHandler (tObj, 999999, &tstTmrHndlr, 0);
  EXEC_TSTCASE (&tstCase, " Register a timer handler.", retVal, retVal,
		ec2ES (retVal), 0);

  retVal = testTimer ();
  EXEC_TSTCASE (&tstCase, " Check the periodicty of the timer (Not Proper)",
		retVal, retVal, ec2ES (retVal), 0);

  retVal = bs_tmodFin (&tObj, iMObj);
  EXEC_TSTCASE (&tstCase, " Finalise the timer module ", retVal, retVal,
		ec2ES (retVal), 0);

  hdr ("Testing of tmod module compleated");
}
