#############################################################################
# Makefile                                                                  #
#############################################################################

target:rpm

include $(CURR_DIR)/Host/com_inc/make_inc.mk

vpath %.c $(SRC_DIR)

COMMISION_RPM = $(RPM_DIR)/commision*.rpm

$(COMMISION_RPM):

rpm:$(COMMISION_RPM)

#############################################################################
