
.PHONY:rpm
rpm:
	$(MAKE) -C S/ rpm
	$(MAKE) -C C/	rpm

.PHONY:tfclean
tfclean:
	$(MAKE) -C S/ tfclean
	$(MAKE) -C C/ tfclean

.PHONY:clean
clean:
	$(MAKE) -C S/ clean
	$(MAKE) -C C/ clean

.PHONY:cleanall
cleanall:
	$(MAKE) -C S/ cleanall
	$(MAKE) -C C/ cleanall
