#############################################################################
# Makefile                                                                  #
#############################################################################

target:rpm

include $(CURR_DIR)/Host/com_inc/make_inc.mk

vpath %.c $(SRC_DIR)

PROVISION_RPM = $(RPM_DIR)/provision*.rpm

$(PROVISION_RPM):

rpm:$(PROVISION_RPM)

#############################################################################
